import type {
  ServiceCategory,
  ServiceItem,
  FaisalabadArea,
  PaymentMethod,
} from '../types';

export const APP_CONFIG = {
  appName: 'USTAD ONLINE',
  tagline: 'Reliable Ustads. Transparent Prices.',
  targetMarket: 'Pakistan (Faisalabad Pilot)',
  defaultCity: 'Faisalabad',
  commissionRate: 0.10, // 10% Platform Commission
  currency: 'Rs.',
  currencyCode: 'PKR',
  supportPhone: '+92 41 8782300',
  supportEmail: 'support@ustadonline.pk',
  demoNotice: 'Simulation Mode: SMS OTP, GPS tracking, and payment gateways operate in functional demo mode.',
};

// ----------------------------------------------------------------------------
// Faisalabad Service Sectors
// ----------------------------------------------------------------------------
export const FAISALABAD_AREAS: FaisalabadArea[] = [
  {
    id: 'd-ground',
    name: 'D-Ground, Peoples Colony No. 1',
    urduName: 'ڈی گراؤنڈ، پیپلز کالونی',
    lat: 31.4124,
    lng: 73.0978,
    radiusKm: 3.5,
    popularFor: 'Commercial & High Density Residential',
  },
  {
    id: 'kohinoor',
    name: 'Kohinoor City, Jaranwala Road',
    urduName: 'کوہ نور سٹی',
    lat: 31.4082,
    lng: 73.1165,
    radiusKm: 2.8,
    popularFor: 'Plaza & Modern Housing',
  },
  {
    id: 'madina-town',
    name: 'Madina Town (Susan Road)',
    urduName: 'مدینہ ٹاؤن، سوسن روڈ',
    lat: 31.4285,
    lng: 73.1114,
    radiusKm: 4.0,
    popularFor: 'Family Homes & Markets',
  },
  {
    id: 'peoples-colony-2',
    name: 'Peoples Colony No. 2',
    urduName: 'پیپلز کالونی نمبر 2',
    lat: 31.3995,
    lng: 73.0882,
    radiusKm: 3.2,
    popularFor: 'Established Residential',
  },
  {
    id: 'ghanta-ghar',
    name: 'Clock Tower / Ghanta Ghar (Bazaars)',
    urduName: 'گھنٹہ گھر، اندرون شہر',
    lat: 31.4187,
    lng: 73.0791,
    radiusKm: 2.5,
    popularFor: 'Central Commercial Hub',
  },
  {
    id: 'ghulam-muhammad-abad',
    name: 'Ghulam Muhammad Abad (GMA)',
    urduName: 'غلام محمد آباد',
    lat: 31.4421,
    lng: 73.0562,
    radiusKm: 4.5,
    popularFor: 'High Volume Artisan Sector',
  },
  {
    id: 'canal-road',
    name: 'Canal Road & Gatwala',
    urduName: 'کینال روڈ و گٹوالا',
    lat: 31.4552,
    lng: 73.1492,
    radiusKm: 5.0,
    popularFor: 'Suburban Societies & Farmhouses',
  },
  {
    id: 'samanabad',
    name: 'Samanabad & Novelty Bridge',
    urduName: 'سمن آباد',
    lat: 31.3854,
    lng: 73.0645,
    radiusKm: 3.8,
    popularFor: 'Densely Populated Residential',
  },
  {
    id: 'millat-town',
    name: 'Millat Town & Sargodha Road',
    urduName: 'ملت ٹاؤن، سرگودھا روڈ',
    lat: 31.4651,
    lng: 73.0789,
    radiusKm: 4.2,
    popularFor: 'North Faisalabad Expansion',
  },
  {
    id: 'jinnah-colony',
    name: 'Jinnah Colony & University Town',
    urduName: 'جناح کالونی',
    lat: 31.4248,
    lng: 73.0722,
    radiusKm: 2.9,
    popularFor: 'Educational & Residential Enclave',
  },
];

// ----------------------------------------------------------------------------
// Six Core Service Categories
// ----------------------------------------------------------------------------
export const SERVICE_CATEGORIES: ServiceCategory[] = [
  {
    id: 'electrician',
    name: 'Electrician',
    iconName: 'Zap',
    description: 'Switchboards, ceiling fans, circuit breakers, UPS & inverter wiring, and emergency fault repairs.',
    startingPrice: 300,
    samplePriceLabel: 'From Rs. 300',
    badge: 'Fast 25-Min Dispatch',
    color: '#2563EB',
    bannerImage: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'plumber',
    name: 'Plumber',
    iconName: 'Droplets',
    description: 'Leaking taps, pipeline blockages, sanitary fittings, water motor pump repair, and overhead tank cleaning.',
    startingPrice: 400,
    samplePriceLabel: 'From Rs. 400',
    badge: 'Equipped Ustads',
    color: '#0284C7',
    bannerImage: 'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'ac-technician',
    name: 'AC Technician',
    iconName: 'Wind',
    description: 'Split & inverter AC master service, gas top-up/refill, compressor diagnostics, and installation/removal.',
    startingPrice: 500,
    samplePriceLabel: 'From Rs. 500',
    badge: 'Seasonal Essential',
    color: '#0891B2',
    bannerImage: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'bike-mechanic',
    name: 'Bike Mechanic',
    iconName: 'Bike',
    description: 'Roadside puncture patching, oil change & tuning, brake shoe replacement, chain sprocket & electrical wiring.',
    startingPrice: 200,
    samplePriceLabel: 'From Rs. 200',
    badge: 'Doorstep & Roadside',
    color: '#D97706',
    bannerImage: 'https://images.unsplash.com/photo-1558981403-c5f9899a28bc?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'car-mechanic',
    name: 'Car Mechanic',
    iconName: 'Car',
    description: 'Engine diagnostics, roadside battery jumpstart, brake pad servicing, radiator coolant leak, and pre-purchase inspection.',
    startingPrice: 800,
    samplePriceLabel: 'From Rs. 800',
    badge: 'Expert Diagnostics',
    color: '#DC2626',
    bannerImage: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 'carpenter',
    name: 'Carpenter',
    iconName: 'Hammer',
    description: 'Door hinge & handle repair, lock replacement, wardrobe sliding track fix, custom shelves, and wood polish.',
    startingPrice: 300,
    samplePriceLabel: 'From Rs. 300',
    badge: 'Precision Finish',
    color: '#7C3AED',
    bannerImage: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=600&auto=format&fit=crop&q=80',
  },
];

// ----------------------------------------------------------------------------
// Rate Card & Service Catalog (Configurable via Admin Panel)
// ----------------------------------------------------------------------------
export const INITIAL_SERVICES: ServiceItem[] = [
  // Electrician
  {
    id: 'srv-elec-01',
    categoryId: 'electrician',
    name: 'Switchboard Repair / Replacement',
    description: 'Fix loose wiring, replace broken switches/sockets, or install new modular switch panel.',
    price: 300,
    pricingType: 'fixed',
    isActive: true,
    estimatedMinutes: 30,
    iconName: 'Zap',
    popular: true,
    possibleExtraCharges: ['New switch or socket plate hardware if needed'],
  },
  {
    id: 'srv-elec-02',
    categoryId: 'electrician',
    name: 'Ceiling Fan Installation & Repair',
    description: 'Fan mounting, capacitor replacement, regulator wiring, or squeaking bearing repair.',
    price: 500,
    pricingType: 'fixed',
    isActive: true,
    estimatedMinutes: 45,
    iconName: 'Fan',
    popular: true,
    possibleExtraCharges: ['Replacement capacitor (approx. Rs. 150-250)'],
  },
  {
    id: 'srv-elec-03',
    categoryId: 'electrician',
    name: 'Short Circuit & Breaker Tripping Diagnostic',
    description: 'Detailed inspection of distribution box, breaker load testing, and isolated line repair.',
    price: 600,
    pricingType: 'estimated',
    isActive: true,
    estimatedMinutes: 60,
    iconName: 'AlertTriangle',
    possibleExtraCharges: ['Replacement breaker switch', 'Concealed copper wire replacement'],
  },
  {
    id: 'srv-elec-04',
    categoryId: 'electrician',
    name: 'UPS & Inverter Wiring Setup',
    description: 'Phase separation, battery terminal cleaning, and inverter load balancing.',
    price: 900,
    pricingType: 'fixed',
    isActive: true,
    estimatedMinutes: 60,
    iconName: 'Cpu',
  },

  // Plumber
  {
    id: 'srv-plum-01',
    categoryId: 'plumber',
    name: 'Tap / Faucet Leak Repair',
    description: 'Washer replacement, cartridge fix, or replacement of kitchen/bathroom mixer faucet.',
    price: 400,
    pricingType: 'fixed',
    isActive: true,
    estimatedMinutes: 30,
    iconName: 'Droplets',
    popular: true,
    possibleExtraCharges: ['New tap spindle or mixer unit'],
  },
  {
    id: 'srv-plum-02',
    categoryId: 'plumber',
    name: 'Drainage Pipe Unclogging / Flushing',
    description: 'Clear grease or debris buildup in kitchen sink, bathroom trap, or main sewer line.',
    price: 650,
    pricingType: 'estimated',
    isActive: true,
    estimatedMinutes: 45,
    iconName: 'Filter',
    popular: true,
    possibleExtraCharges: ['Specialized chemical solvent or motorized snake clean'],
  },
  {
    id: 'srv-plum-03',
    categoryId: 'plumber',
    name: 'Water Motor Pump Servicing',
    description: 'Impeller inspection, seal replacement, priming check, and capacitor check for electric motor.',
    price: 850,
    pricingType: 'estimated',
    isActive: true,
    estimatedMinutes: 60,
    iconName: 'RotateCw',
    possibleExtraCharges: ['Bearing replacement', 'Rewinding if stator damaged'],
  },
  {
    id: 'srv-plum-04',
    categoryId: 'plumber',
    name: 'Overhead Water Tank Cleaning',
    description: 'Complete draining, high-pressure scrubbing, chlorine disinfection, and sediment flush.',
    price: 1400,
    pricingType: 'fixed',
    isActive: true,
    estimatedMinutes: 90,
    iconName: 'ShieldCheck',
  },

  // AC Technician
  {
    id: 'srv-ac-01',
    categoryId: 'ac-technician',
    name: 'AC Diagnostic & Cooling Inspection',
    description: 'Thorough inspection of compressor health, gas pressure, airflow temperature, and electrical amp draw.',
    price: 500,
    pricingType: 'estimated',
    isActive: true,
    estimatedMinutes: 40,
    iconName: 'Search',
    popular: true,
    possibleExtraCharges: ['Gas refill cost if leak found', 'PCB circuit card repair'],
  },
  {
    id: 'srv-ac-02',
    categoryId: 'ac-technician',
    name: 'Split AC Master Chemical Wash',
    description: 'Indoor blower jet wash, coil chemical deep clean, outdoor condenser flush, and drain pipe clearance.',
    price: 1500,
    pricingType: 'fixed',
    isActive: true,
    estimatedMinutes: 75,
    iconName: 'Wind',
    popular: true,
  },
  {
    id: 'srv-ac-03',
    categoryId: 'ac-technician',
    name: 'Refrigerant R32 / R410A Gas Top-up',
    description: 'System leak test with soap solution, flare nut tightening, vacuuming, and verified PSI charge.',
    price: 2800,
    pricingType: 'estimated',
    isActive: true,
    estimatedMinutes: 60,
    iconName: 'Gauge',
    possibleExtraCharges: ['Copper pipe flare weld or brass valve replacement'],
  },
  {
    id: 'srv-ac-04',
    categoryId: 'ac-technician',
    name: 'AC Installation / Relocation',
    description: 'Indoor & outdoor bracket mounting, hole core drilling, and copper line routing.',
    price: 2200,
    pricingType: 'fixed',
    isActive: true,
    estimatedMinutes: 90,
    iconName: 'Layers',
  },

  // Bike Mechanic
  {
    id: 'srv-bike-01',
    categoryId: 'bike-mechanic',
    name: 'Doorstep Bike Puncture Repair (Tube/Tubeless)',
    description: 'Wheel removal, leak detection in water tray, cold patch application, and tire pressure restoration.',
    price: 200,
    pricingType: 'fixed',
    isActive: true,
    estimatedMinutes: 25,
    iconName: 'CircleDot',
    popular: true,
    possibleExtraCharges: ['New tube if old tube has blowout (approx. Rs. 400)'],
  },
  {
    id: 'srv-bike-02',
    categoryId: 'bike-mechanic',
    name: 'Motorcycle Tuning & Engine Oil Service',
    description: 'Tappet clearance adjustment, carburetor cleaning, spark plug check, chain lube, and oil drainage.',
    price: 450,
    pricingType: 'fixed',
    isActive: true,
    estimatedMinutes: 45,
    iconName: 'Wrench',
    popular: true,
    possibleExtraCharges: ['Engine oil bottle cost (Havoline/Caltex/ZIC)'],
  },
  {
    id: 'srv-bike-03',
    categoryId: 'bike-mechanic',
    name: 'Brake Shoe Replacement (Front/Rear)',
    description: 'Drum cleaning, spring fitting, and brake wire cable tension adjustment.',
    price: 350,
    pricingType: 'fixed',
    isActive: true,
    estimatedMinutes: 35,
    iconName: 'Disc',
    possibleExtraCharges: ['New brake shoe set parts'],
  },
  {
    id: 'srv-bike-04',
    categoryId: 'bike-mechanic',
    name: 'Chain & Sprocket Kit Replacement',
    description: 'Chain link adjustment, rear hub inspection, and sprocket realignment.',
    price: 500,
    pricingType: 'fixed',
    isActive: true,
    estimatedMinutes: 50,
    iconName: 'Settings',
  },

  // Car Mechanic
  {
    id: 'srv-car-01',
    categoryId: 'car-mechanic',
    name: 'Car Roadside Inspection & Diagnostic',
    description: 'OBD-II scanner check, engine noise inspection, coolant system check, and electrical test.',
    price: 800,
    pricingType: 'estimated',
    isActive: true,
    estimatedMinutes: 45,
    iconName: 'Search',
    popular: true,
    possibleExtraCharges: ['Towing assistance if non-drivable', 'Part procurement fee'],
  },
  {
    id: 'srv-car-02',
    categoryId: 'car-mechanic',
    name: 'Emergency Battery Jumpstart & Alternator Test',
    description: 'Heavy-duty jumper cable start, alternator charging voltage check, and terminal corrosion clean.',
    price: 600,
    pricingType: 'fixed',
    isActive: true,
    estimatedMinutes: 30,
    iconName: 'BatteryCharging',
    popular: true,
  },
  {
    id: 'srv-car-03',
    categoryId: 'car-mechanic',
    name: 'Brake Pad Replacement & Disc Inspection',
    description: 'Caliper servicing, brake pad mounting, and brake fluid bleeding check.',
    price: 1200,
    pricingType: 'fixed',
    isActive: true,
    estimatedMinutes: 60,
    iconName: 'Disc',
    possibleExtraCharges: ['Cost of new OEM/aftermarket brake pads'],
  },
  {
    id: 'srv-car-04',
    categoryId: 'car-mechanic',
    name: 'Full Doorstep Oil & Filter Service',
    description: 'Sump plug drain, oil filter replacement, air filter cleaning, and fluids top-up check.',
    price: 900,
    pricingType: 'fixed',
    isActive: true,
    estimatedMinutes: 45,
    iconName: 'Droplet',
  },

  // Carpenter
  {
    id: 'srv-carp-01',
    categoryId: 'carpenter',
    name: 'Door Hinge Repair & Alignment',
    description: 'Tighten sagged door hinges, plane door edges if scraping against floor, and grease pins.',
    price: 300,
    pricingType: 'fixed',
    isActive: true,
    estimatedMinutes: 35,
    iconName: 'Hammer',
    popular: true,
    possibleExtraCharges: ['New brass/steel hinge set if stripped'],
  },
  {
    id: 'srv-carp-02',
    categoryId: 'carpenter',
    name: 'Main Door Lock / Deadbolt Replacement',
    description: 'Cylinder removal, wood mortise chiseling, handle fitting, and strike plate alignment.',
    price: 550,
    pricingType: 'fixed',
    isActive: true,
    estimatedMinutes: 45,
    iconName: 'Lock',
    popular: true,
    possibleExtraCharges: ['New lock set (customer supplied or Ustad purchased)'],
  },
  {
    id: 'srv-carp-03',
    categoryId: 'carpenter',
    name: 'Sliding Wardrobe Track & Roller Fix',
    description: 'Door removal, track leveling, wheel replacement, and smooth slide adjustment.',
    price: 700,
    pricingType: 'estimated',
    isActive: true,
    estimatedMinutes: 60,
    iconName: 'Sliders',
    possibleExtraCharges: ['Heavy-duty bearing rollers'],
  },
  {
    id: 'srv-carp-04',
    categoryId: 'carpenter',
    name: 'Custom Wooden Shelving / Furniture Assembly',
    description: 'Flat-pack IKEA/local furniture assembly, wall bracket anchoring, and leveling.',
    price: 850,
    pricingType: 'estimated',
    isActive: true,
    estimatedMinutes: 75,
    iconName: 'Grid',
  },
];

// ----------------------------------------------------------------------------
// Sample Problem Photos for Instant Demo Selection
// ----------------------------------------------------------------------------
export const SAMPLE_PROBLEM_PHOTOS = [
  {
    id: 'photo-switch',
    title: 'Burnt Switchboard',
    url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=500&auto=format&fit=crop&q=80',
    category: 'electrician',
  },
  {
    id: 'photo-tap',
    title: 'Leaking Sink Tap',
    url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=500&auto=format&fit=crop&q=80',
    category: 'plumber',
  },
  {
    id: 'photo-ac',
    title: 'AC Outdoor Unit Dust',
    url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&auto=format&fit=crop&q=80',
    category: 'ac-technician',
  },
  {
    id: 'photo-tire',
    title: 'Flat Motorcycle Tire',
    url: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=500&auto=format&fit=crop&q=80',
    category: 'bike-mechanic',
  },
  {
    id: 'photo-car',
    title: 'Car Battery Terminals',
    url: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=500&auto=format&fit=crop&q=80',
    category: 'car-mechanic',
  },
  {
    id: 'photo-door',
    title: 'Broken Door Hinge',
    url: 'https://images.unsplash.com/photo-1533090161767-e6ffed986c88?w=500&auto=format&fit=crop&q=80',
    category: 'carpenter',
  },
];

// ----------------------------------------------------------------------------
// Pre-Canned Chat Quick Responses
// ----------------------------------------------------------------------------
export const CHAT_QUICK_REPLIES = {
  customer: [
    'Where have you reached, Ustad Ji?',
    'I am waiting near the main gate.',
    'Please bring a spare capacitor if possible.',
    'Is the estimated price confirmed?',
    'Thank you, excellent work!',
  ],
  ustad: [
    'Salam! I have left the workshop, reaching in 10 minutes.',
    'I am outside your building/street now.',
    'I am inspecting the problem and tools are ready.',
    'Job done! Please review and verify the switch.',
    'Thank you, please leave a 5-star rating on the app!',
  ],
};

// ----------------------------------------------------------------------------
// Payment Methods Configuration
// ----------------------------------------------------------------------------
export const PAYMENT_METHODS: Array<{
  id: PaymentMethod;
  name: string;
  badge: string;
  description: string;
  iconName: string;
}> = [
  {
    id: 'cash',
    name: 'Cash on Delivery (COD)',
    badge: 'Popular',
    description: 'Pay cash directly to Ustad after job inspection and completion.',
    iconName: 'Banknote',
  },
  {
    id: 'easypaisa',
    name: 'Easypaisa Mobile Wallet',
    badge: 'Instant Instant',
    description: 'Instant transfer via Telenor Microfinance / 03XX-XXXXXXX.',
    iconName: 'Smartphone',
  },
  {
    id: 'jazzcash',
    name: 'JazzCash Wallet',
    badge: 'Instant Instant',
    description: 'Pay through JazzCash App or USSD *786#.',
    iconName: 'CreditCard',
  },
];
